### ISSUE TITLE
Strange behaviour: potential bug?

### ISSUE THREAD

**Issue by matteodefelice** [sieste/SpecsVerification#1]
Here the simple example:
```
tm = GenerateToyData()
ens = (tm$ens >= quantile(tm$ens, 2/3))*1.0
obs = (tm$obs >= quantile(tm$obs, 2/3))*1.0
e1 = EnsRps(ens, obs)
```
I would expect, as said in the documentation, to have `e1` a "numeric vector of length N" but instead:
```
> e1 = EnsRps(ens, obs)
> e1
[1] 225.6616
```
Both `ens` and `obs` seem consistent with the needed input, maybe `EnsRps` does not accept binary categories?

**Comment by sieste** [comment]
Thanks for reporting this, Matteo. This behavior is due to poor function documentation.

`EnsRps` internally uses `tabulate` to count the number of occurrences of each category. `tabulate` expects positive integers, while in your ensemble data there are zeros. So simply adding 1 to both `ens` and `obs` in the example makes the categories positive and the result is a vector of scores. Could you please confirm that the behavior is now as expected?

**Comment by matteodefelice** [comment]
Yes, adding 1 fixes the pseudo-bug! Thanks!

**Comment by sieste** [comment]
I have added a note in the function documentation and a check for positive category labels in commit 7034e87
